baseURL = "https://muscaestar.github.io/myBlog/"
#languageCode = "en-us"
metaDataFormat = "yaml"
title = "Muscaestar's Blog"
theme = "beautifulhugo"
#pygmentsStyle = "trac"
#pygmentsUseClasses = true
#pygmentsCodeFences = true
#pygmentsCodefencesGuessSyntax = true
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = true
[languages]
  [languages.en]
    contentDir = "content/en" #English
    weight = 1
    languageName = "English"
    subtitle = "Your day starts the night before."
    [languages.en.params]
      linkedin = "https://muscaestar.github.io/myBlog/en/"
    [[languages.en.menu.main]]
        name = "Blog"
        url = ""
        weight = 1

    [[languages.en.menu.main]]
        name = "About"
        url = "page/about/"
        weight = 3

    [[languages.en.menu.main]]
        identifier = "Projects"
        name = "Projects"
        weight = 2

    [[languages.en.menu.main]]
        parent = "Projects"
        name = "In Progress"
        url = ""
        weight = 1

    # [[languages.en.menu.main]]
    #     parent = "Projects"
    #     name = "Math Sample"
    #     url = "post/2017-03-05-math-sample"
    #     weight = 2

    [[languages.en.menu.main]]
        name = "Tags"
        url = "tags"
        weight = 3
  [languages.zh-CN]
    contentDir = "content/zh-CN" #Simplified Chinese
    weight = 2
    languageName = "简体中文"
    subtitle = "今日始于昨夜"
    [languages.zh-CN.params]
      linkedin = "https://muscaestar.github.io/myBlog/zh-CN/"
    [[languages.zh-CN.menu.main]]
        name = "博客"
        url = ""
        weight = 1

    [[languages.zh-CN.menu.main]]
        name = "关于"
        url = "page/about/"
        weight = 3

    [[languages.zh-CN.menu.main]]
        identifier = "Projects"
        name = "项目"
        weight = 2

    [[languages.zh-CN.menu.main]]
        parent = "Projects"
        name = "In Progress"
        url = ""
        weight = 1

    [[languages.zh-CN.menu.main]]
        name = "标签"
        url = "tags"
        weight = 3

[Params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  mainSections = ["post","posts"]
  logo = "img/rika-avatar-480.jpeg" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = false
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = false
  socialShare = false
  delayDisqus = false
  showRelatedPosts = true
  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Muscaestar"
  #website = "muscaestar.github.io/myBlog"
  #email = "muscaestar@hotmail.com"
  github = "muscaestar"
  # facebook = "username"
  # gitlab = "username"
  # bitbucket = "username"
  # twitter = "username"
  # reddit = "username"
  # linkedin = "username"
  # xing = "username"
  # stackoverflow = "users/XXXXXXX/username"
  # snapchat = "username"
  # instagram = "username"
  # youtube = "user/username" # or channel/channelname
  # soundcloud = "username"
  # spotify = "username"
  # bandcamp = "username"
  # itchio = "username"
  # vk = "username"
  # paypal = "username"
  # telegram = "username"
  # 500px = "username"
  # codepen = "username"
  # mastodon = "url"
  # kaggle = "username"
  # weibo = "username"
  # slack = "username"

